services:
  oder-db:
    image: postgres:15
    container_name: oder-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anh14112004
      POSTGRES_DB: oder-db
    ports:
      - "5433:5432"
    volumes:
      - order:/var/lib/postgresql/data

volumes:
  order:
